exports.studentsListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <title>Student Management</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    background-color: #f4f4f4;
                    margin: 0;
                    padding: 0;
                }

                .w3-card-4 {
                    margin: 20px;
                    padding: 20px;
                    border-radius: 8px;
                    background-color: white;
                    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
                }

                header {
                    background-color: #009688;
                    color: white;
                    padding: 15px;
                    border-radius: 8px;
                }

                header h1 {
                    margin: 0;
                }

                table {
                    width: 100%;
                    border-collapse: collapse;
                    margin-top: 20px;
                }

                th, td {
                    padding: 10px;
                    text-align: left;
                    border-bottom: 1px solid #ddd;
                }

                th {
                    background-color: #f2f2f2;
                }

                td a {
                    text-decoration: none;
                    color: #009688;
                }

                td a:hover {
                    text-decoration: underline;
                }

                footer {
                    background-color: #009688;
                    color: white;
                    padding: 10px;
                    text-align: center;
                    margin-top: 20px;
                }

                .w3-btn {
                    background-color: #009688;
                    color: white;
                    padding: 8px 16px;
                    text-decoration: none;
                    border-radius: 4px;
                    margin-left: 10px;
                }

                .w3-btn:hover {
                    background-color: #00796b;
                }

                .w3-table-all {
                    width: 100%;
                    border-collapse: collapse;
                }

                .w3-table-all th, .w3-table-all td {
                    padding: 10px;
                    text-align: left;
                    border-bottom: 1px solid #ddd;
                }

                .w3-table-all th {
                    background-color: #f2f2f2;
                }
            </style>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container">
                    <h1>Students List
                    <a class="w3-btn" href="/alunos/registo">+</a>
                    </h1>
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>GitLink</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i = 0; i < slist.length; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/alunos/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>${slist[i].git}</td>
                    <td>
                        [<a href="/alunos/edit/${slist[i].id}">Edit</a>][<a href="/alunos/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container">
                    <h5>Generated by RPCW2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}



exports.studentFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <title>Student Form</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    background-color: #f4f4f4;
                    margin: 0;
                    padding: 0;
                }

                .w3-card-4 {
                    margin: 20px;
                    padding: 20px;
                    border-radius: 8px;
                    background-color: white;
                    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
                }

                header {
                    background-color: #9c27b0;
                    color: white;
                    padding: 15px;
                    border-radius: 8px;
                }

                form {
                    margin-top: 20px;
                }

                label {
                    display: block;
                    margin: 10px 0 5px;
                    font-weight: bold;
                }

                input[type="text"], input[type="checkbox"] {
                    margin-bottom: 10px;
                }

                button {
                    background-color: #9c27b0;
                    color: white;
                    padding: 10px 20px;
                    border: none;
                    border-radius: 4px;
                    cursor: pointer;
                }

                button:hover {
                    background-color: #7b1fa2;
                }

                footer {
                    background-color: #9c27b0;
                    color: white;
                    padding: 10px;
                    text-align: center;
                }

            </style>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" required />
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                        <label>Git</label>
                        <input class="w3-input w3-round" type="text" name="git" required/>
                    </fieldset>

                    <fieldset>
                        <legend>TPC</legend>
                        <input class="w3-check" type="checkbox" name="tpc1" value="1"/>
                        <label>TPC1</label>
                        <input class="w3-check" type="checkbox" name="tpc2" value="1"/>
                        <label>TPC2</label>
                        <input class="w3-check" type="checkbox" name="tpc3" value="1"/>
                        <label>TPC3</label>
                        <input class="w3-check" type="checkbox" name="tpc4" value="1"/>
                        <label>TPC4</label>
                        <input class="w3-check" type="checkbox" name="tpc5" value="1"/>
                        <label>TPC5</label>
                        <input class="w3-check" type="checkbox" name="tpc6" value="1"/>
                        <label>TPC6</label>
                        <input class="w3-check" type="checkbox" name="tpc7" value="1"/>
                        <label>TPC7</label>
                        <input class="w3-check" type="checkbox" name="tpc8" value="1"/>
                        <label>TPC8</label>
                    </fieldset>  
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.studentFormEditPage = function(a, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <title>Student Form</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    background-color: #f4f4f4;
                    margin: 0;
                    padding: 0;
                }

                .w3-card-4 {
                    margin: 20px;
                    padding: 20px;
                    border-radius: 8px;
                    background-color: white;
                    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
                }

                header {
                    background-color: #ff9800;
                    color: white;
                    padding: 15px;
                    border-radius: 8px;
                }

                form {
                    margin-top: 20px;
                }

                label {
                    display: block;
                    margin: 10px 0 5px;
                    font-weight: bold;
                }

                input[type="text"], input[type="checkbox"] {
                    margin-bottom: 10px;
                }

                button {
                    background-color: #ff9800;
                    color: white;
                    padding: 10px 20px;
                    border: none;
                    border-radius: 4px;
                    cursor: pointer;
                }

                button:hover {
                    background-color: #f57c00;
                }

                footer {
                    background-color: #ff9800;
                    color: white;
                    padding: 10px;
                    text-align: center;
                }

            </style>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-orange">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}" required />
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}" required />
                        <label>Git</label>
                        <input class="w3-input w3-round" type="text" name="git" value="${a.git}" required />
                    </fieldset>

                    <fieldset>
                        <legend>TPC</legend>
                    `

    for(i = 1; i < 9; i++){
        var tpc = "tpc" + i
        if(tpc in a){
            pagHTML += `<input class="w3-check" type="checkbox" name="tpc${i}" value="1" checked/>
                        <label>TPC${i}</label>
                        `
        }
        else{
            pagHTML += `<input class="w3-check" type="checkbox" name="tpc${i}" value="1"/>
                        <label>TPC${i}</label>
                        `
        }
    }

    pagHTML += `
                    </fieldset>  
                    <br/>
                    <button class="w3-btn w3-orange w3-mb-2" type="submit">Edit</button>
                </form>

                <footer class="w3-container w3-orange">
                    <h5>Generated by EngWeb2025 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}


// ---------------Student's Page--------------------------------
exports.studentPage = function( aluno, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Aluno: ${aluno.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                margin: 0;
                padding: 0;
            }

            .w3-card-4 {
                margin: 20px;
                padding: 20px;
                border-radius: 8px;
                background-color: white;
                box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
            }

            header {
                background-color: #009688;
                color: white;
                padding: 15px;
                border-radius: 8px;
            }

            footer {
                background-color: #009688;
                color: white;
                padding: 10px;
                text-align: center;
            }

            .w3-ul {
                list-style-type: none;
                padding: 0;
            }

            .w3-ul li {
                padding: 10px;
                border-bottom: 1px solid #ddd;
            }

            .w3-ul li b {
                font-weight: bold;
            }

        </style>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Aluno ${aluno.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${aluno.nome}</li>
                    <li><b>Número: </b> ${aluno.id}</li>
                    <li><b>Git (link): </b> <a href="${aluno.git}">${aluno.git}</a></li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
            `
            for(let i = 1; i < 9; i++){
                key = `tpc${i}`
                if(key in aluno){
                    pagHTML += `
                        <li><b>TPC${i}</b></li>
                    `
                }
            }

    pagHTML += `</ul></div>
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}


exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}