exports.logos = {
    "Alfa Romeo":"https://www.izmostock.com/wp-content/uploads/2015/12/alfaromeo.png",
    "Aston Martin":"https://www.izmostock.com/wp-content/uploads/2015/12/Aston-Martin.png",
    "Audi":"https://www.izmostock.com/wp-content/uploads/2015/12/Audi.png",
    "Bentley":"https://www.izmostock.com/wp-content/uploads/2015/12/bentley.png",
    "BMW": "https://www.izmostock.com/wp-content/uploads/2015/12/BMW.png",
    "Cadillac": "https://www.izmostock.com/wp-content/uploads/2015/12/Cadillac.png",
    "Chery": "https://www.carlogos.org/logo/Chery-logo-2013-640x346.jpg",
    "Chevrolet": "https://www.izmostock.com/wp-content/uploads/2015/12/Chevrolet.png",
    "Chrysler": "https://www.izmostock.com/wp-content/uploads/2015/12/chrysler.png",
    "Citroen": "https://www.izmostock.com/wp-content/uploads/2015/12/Citroen_izmostock.png",
    "Dacia": "https://www.izmostock.com/wp-content/uploads/2015/12/Dacia.png",
    "Daewoo": "https://via.placeholder.com/200?text=Daewoo",
    "Daihatsu": "https://via.placeholder.com/200?text=Daihatsu",
    "DFM": "https://www.carlogos.org/logo/Dongfeng-logo-640x550.jpg",
    "Dodge": "https://www.izmostock.com/wp-content/uploads/2015/12/Dodge.png",
    "Ferrari": "https://www.izmostock.com/wp-content/uploads/2015/12/Ferrari.png",
    "Fiat": "https://www.izmostock.com/wp-content/uploads/2015/12/fiat-1.png",
    "Ford": "https://www.izmostock.com/wp-content/uploads/2015/12/Ford.png",
    "Geely": "https://www.carlogos.org/logo/Geely-logo-2014-640x370.jpg",
    "Honda": "https://www.izmostock.com/wp-content/uploads/2015/12/honda.png",
    "Hyundai": "https://www.izmostock.com/wp-content/uploads/2015/12/Hyundai.png",
    "Infiniti": "https://www.izmostock.com/wp-content/uploads/2015/12/infinity.png",
    "Isuzu": "https://www.izmostock.com/wp-content/uploads/2015/12/Isuzu.png",
    "Jaguar": "https://www.izmostock.com/wp-content/uploads/2015/12/Jaguar.png",
    "Jeep": "https://www.izmostock.com/wp-content/uploads/2015/12/Jeep.png",
    "Kia": "https://www.izmostock.com/wp-content/uploads/2015/12/kia-1.png",
    "Lada": "https://www.carlogos.org/logo/Lada-logo-silver-640x248.jpg",
    "Lamborghini": "https://www.izmostock.com/wp-content/uploads/2015/12/Lamborghini.png",
    "Lancia": "https://www.izmostock.com/wp-content/uploads/2015/12/lancia-1.png",
    "Land Rover": "https://www.izmostock.com/wp-content/uploads/2015/12/landrover.png",
    "Maserati": "https://www.izmostock.com/wp-content/uploads/2015/12/maserati.png",
    "Mazda": "https://www.izmostock.com/wp-content/uploads/2015/12/mazda-1.png",
    "Mercedes": "https://www.izmostock.com/wp-content/uploads/2015/12/Mercedes-Benz.png",
    "Mini": "https://www.izmostock.com/wp-content/uploads/2015/12/Mini.png",
    "Mitsubishi": "https://www.izmostock.com/wp-content/uploads/2015/12/Mitsubishi.png",
    "Nissan": "https://www.izmostock.com/wp-content/uploads/2015/12/Nissan.png",
    "Opel": "https://www.izmostock.com/wp-content/uploads/2015/12/Opel.png",
    "Peugeot": "https://www.izmostock.com/wp-content/uploads/2015/12/Peugeot.png",
    "Porsche": "https://www.izmostock.com/wp-content/uploads/2015/12/Porsche.png",
    "Proton": "https://www.carlogos.org/logo/Proton-logo-2016-640x550.jpg",
    "Renault": "https://www.izmostock.com/wp-content/uploads/2015/12/Renault.png",
    "Rover": "https://upload.wikimedia.org/wikipedia/pt/thumb/d/db/Logotipo_da_Rover_de_2003.png/200px-Logotipo_da_Rover_de_2003.png",
    "Saab": "https://www.carlogos.org/logo/Saab-logo-2002-640x550.jpg",
    "Seat": "https://www.izmostock.com/wp-content/uploads/2015/12/Seat.png",
    "Skoda": "https://www.izmostock.com/wp-content/uploads/2015/12/Skoda.png",
};